# Generated by Django 5.1.4 on 2024-12-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmodel',
            old_name='morf_file',
            new_name='morf_json',
        ),
    ]
